import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import NavBar from '../component/NavBar'
import SideBar from '../component/SideBar'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [sideOpen, setSideOpen] = useState(false)
  return (
    <div className={styles.container}>
      <Head>
        <title>Winnie Bolm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/img/logo.png" />
      </Head>
      <NavBar sideOpen={sideOpen} setSideOpen={setSideOpen} />
      <SideBar sideOpen={sideOpen} setSideOpen={setSideOpen}/>
    </div>
  )
}
